### ISSUE TITLE
(Tracking) Issue with Broker URL with introduction of broker class

### ISSUE THREAD

**Issue by akashrv** [google/knative-gcp#1020]
This is tracking issue. 
Original issue: https://github.com/knative/eventing/issues/3097

**Comment by grantr** [comment]
I think this is something we should bump in priority. Being able to target `http://default-broker` is a powerful convenience for prototyping. Yes, SinkBinding is a work around with some nice features, but it's additional complexity for the user to learn about, AND it places constraints on the app (must get the URI from K_SINK). Some containers won't be able to use SinkBinding due to not conforming to its interface, like the performance test image, which takes the target url as an argument. 

Just like we were considering creating brokers in namespaces automatically as a convenience, we could create Services in namespaces alongside Brokers automatically as a convenience. The Broker ingress would need to be updated to accept requests on `/` and attempt to retrieve the broker key from the host value.

The path-based URI should remain canonical and the Addressable URI, since it's necessary for TLS to work and the complexity of the URI doesn't matter when using Addressable resolution.

**Comment by grantr** [comment]
P1 R2: Investigating whether this is a useful feature

**Comment by liu-cong** [comment]
I think it could be confusing if both URLs are supported without explicit input from the user. We can make this configurable by leveraging the `Config` field in broker spec. Maybe we use the service based URL by default, and let users to configure it to be path based if they need TLS.
