### ISSUE TITLE
Limitation to add unit test for SetDefaults() related to clusterName annotation.

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1037]
**Describe the bug**
There is a limitation to add unit test for SetDeafults() related to clusterName annotation.
If we directly use SetDefaults(), it can't take a testing metadate client in. Thus, unless specifying clusterName annotation here, in local, it will show no cluster name annotation, but in prow, it will show cluster name annotation for the prow job project...

 **Expected behavior**

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative-GCP release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by grantr** [comment]
Another way to describe this issue is: The SetDefaults() code for some resources relies on the presence of the GCE metadata server and doesn't allow mocking it. This makes the results of unit tests different in GCE and non-GCE environments. A fix would involve mocking the metadata server (or client) for unit tests that call SetDefaults.
