### ISSUE TITLE
 Add the cluster-name functionality to resources that need it

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#1055]
**Problem**
Once PR #950 lands, controller can get clusterName from resource's annotation (if it is running in GKE). Using this issue to track if resources need to include cluster-name.

- For WI https://github.com/google/knative-gcp/issues/715
- For GCP Broker https://github.com/google/knative-gcp/issues/978

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
If we want to do any renames for R2, we should probably determine and plan that before R1.

**Comment by grantr** [comment]
Scoping the P1 exit criteria of this down to:
- Determine if cluster name can change during the lifetime of a cluster
- understand how cluster name affects cross-cluster correctness for all resources
- List resources that would gain improved correctness from having cluster name available during reconcile and create issue for each

Implementation priority can be determined on per-resource issues.

**Comment by grantr** [comment]
It does not appear possible to change the cluster name in the UI or CLI.

The [K8s docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/) state that UIDs are UUIDs (the implementation currently uses [random UUIDs](https://github.com/kubernetes/apimachinery/blob/76330795f827e44ffc47f4fdc8e0d39872bead8f/pkg/util/uuid/uuid.go#L26)) so they should be unique across clusters.

Since #1207, all GCP resources owned by K8s objects include the K8s UID in their names. Thus, cluster name is not needed in the name to achieve correctness because the UID provides universal uniqueness.

Since no resources gain improved correctness from having cluster name in their resource name, I'm downgrading this to P2. When this is revisited, we should consider whether the user is better served by a GCP resource label containing the cluster name.

**Comment by grantr** [comment]
Closing this for now. It's no longer clear this is a good idea and cluster name is kind of hard to get.
