### ISSUE TITLE
Source can still be ready even though relevant sink k8s service does exist

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1171]
**Describe the bug**
Source can still be ready even though relevant sink kubernetes service does exist

 **Expected behavior**
Source should not be ready when relevant sink kubernetes service doesn't exist and it should show some info in status like `SinkDoesNotExist`

 **To Reproduce**
Steps to reproduce the behavior.
`k apply -f https://github.com/google/knative-gcp/blob/master/docs/examples/cloudpubsubsource/cloudpubsubsource.yaml` without creating kubernetes service `event-display`
 **Knative-GCP release version**

 **Additional context**
In addition, all relevant E2E smoke tests related to sources should get updated after we fix this issue(currently, we don't create k8s service in those E2E smoke tests).
Code need to change in pkg: https://github.com/knative/pkg/blob/389d28f9b67a4650417472c2cf8aa15238e46555/resolver/addressable_resolver.go#L152

**Comment by nachocano** [comment]
I think there was a pkg issue regarding this. If there is no issue, I think we should file one in pkg. IIRC you found it long time back but we might have missed to file the bug.
This problem is for everyone using a v1 k8s Service as sink, not just Sources.
I'm not sure this is a release1, p1, but I might be wrong. We can discuss offline about the priority
