### ISSUE TITLE
Move all E2E tests related to MT broker with pubsub channel to a different test repo

### ISSUE THREAD

**Issue by capri-xiyue** [google/knative-gcp#1177]
**Problem**
Move  all E2E tests related to MT broker with pubsub channel to a separate conformance test package (in knative-gcp) 
and create individual workflow for conformance test like what knative-eventing does

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by capri-xiyue** [comment]
Not sure whether we can delete these E2E tests since channel based broker or MT broker might fail when they runs with pubsub channel

**Comment by tommyreddad** [comment]
@capri-xiyue @nlopezgi The MTBroker with pub/sub channel tests are now working ever since https://github.com/knative/eventing/pull/3612.

Knative-GCP currently does not distinguish between conformance and e2e tests, so this issue seems to also involve creating that distinction. Do we want to replicate the repo structure for knative/eventing? The current knative-gcp hierarchy is
- test
  - e2e
    - lib

while in knative/eventing it is

- test
  - lib
  - conformance
  - e2e

**Comment by nlopezgi** [comment]
I do think in general its better to replicate the repo structure from usptream, unless there is a reason not to do so for our case.

**Comment by capri-xiyue** [comment]
Another point of this issue is to create separate testgrid for conformance test like what knative-eventing does instead of combining all the e2e and conformance tests in the same testgrid
