### ISSUE TITLE
Make brokercell creation and garbage collection logic a separate controller

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#1196]
**Problem**
I chose to embed the logic in broker and brokercell controllers initially for development speed. But it's cleaner to separate the logic into its own controller. 

* BrokercellCreation: https://github.com/google/knative-gcp/pull/1132
* Brokercell GC: https://github.com/google/knative-gcp/pull/1162

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**

**Comment by grantr** [comment]
Slight complication to this strategy: there is a race between the Broker controller and the BrokerCell creation controller. The initial reconcile of the Broker *may* result in the Broker's Ready condition briefly being False if the BrokerCell does not yet exist. This brief False status can be an issue for clients which rely on the terminal nature of False to know when to stop waiting and tell their users that an error has occurred.

Technically, a combined Broker controller can avoid this by setting the relevant condition to Unknown instead of False when it chooses to create a BrokerCell.

**Comment by liu-cong** [comment]
Can this be worked around by setting the condition to `Unknown` instead of `False`?

**Comment by grantr** [comment]
Yes. Technically it is inaccurate since the Broker controller alone cannot know if the BrokerCell will eventually be created. A BrokerCell that is never created for whatever reason will leave the Broker in Unknown status forever, OR the Broker controller must implement timeout logic to know when the status should become False.

This has been debated in various issues, but the only one I can find right now is https://github.com/knative/serving/issues/6784.
