### ISSUE TITLE
ko apply -f config fails: no endpoints available for service webhook

### ISSUE THREAD

**Issue by ian-mi** [google/knative-gcp#1234]
**Describe the bug**
When initially installing knative-gcp the webhook pod will fail to start with the error `configmap "config-gcp-auth" not found`. Configmap creation will then fail attempting to call the webhook causing installation to fail. This circular dependency is impossible to recover from without deleting the webhook rule. The correct installation order seems to be to first install the configmaps and only afterwards install the webhook rule.

 **Expected behavior**
ko apply -f config should succeed.

 **To Reproduce**
Run ko apply -f config in a cluster without knative-gcp already installed.

 **Knative-GCP release version**
master

**Comment by ian-mi** [comment]
I think the issue here is that webhook configuration is global and will not be deleted when the cloud-run-events ns is deleted. I'm not sure if there's any way around this.

**Comment by Harwayne** [comment]
This is similar to https://github.com/knative/eventing/issues/3244. 

As far as I am aware, this should work fine as long as everything is running. It becomes a problem when the webhook stops for some reason, but has already registered itself as required for ConfigMap mutations. 

It is also fine during initial install, because the Webhook itself is registering as required for ConfigMap mutations during its startup process.

This becomes a problem if somehow you have a failing webhook and invalid ConfigMap values.

**Comment by nachocano** [comment]
Based on @Harwayne explanation, do we still think this is a P1? Seems more like a P2 to me?
@ian-mi WDYT?

BTW, seems like it's not a Sources problem. I think we need another project area in knative-gcp. Security might be useful to have, as I've seen some WI-related issues as well.

**Comment by yolocs** [comment]
Test if the case eventing on -> off -> on will cause this problem

**Comment by Harwayne** [comment]
> Test if the case eventing on -> off -> on will cause this problem

Manually tested. Everything works correctly. The `ValidatingWebhookConfiguration` is deleted during the 'off' stage, so no problems occur when turned back to 'on'.

/close
