### ISSUE TITLE
Export broker data plane logs as test artifacts

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1417]
**Problem**
Useful for debugging flaky delivery issues

**Comment by yolocs** [comment]
It turned out we do have logs from broker data plane (_usually_).

They are dumped as part of this function: 

https://github.com/google/knative-gcp/blob/f7a6351211526cd3df0e261ad20599b484521d1c/test/e2e-common.sh#L105-L128

Such logs will be located at artifacts/controller-logs with names like `cloud-run-events-default-brokercell-fanout-86bb65f9df-v2j49-fanout.txt`

Although they don't always present for some reason. I suspect it's because sometimes broker data plane pods were deleted before it dumps.

**Comment by yolocs** [comment]
On test failure, we will tear down the test namespace which will also deletes the broker. If all the brokers are deleted and the GC happens to recycle the broker data plane, we will end up not having broker data plane pods to dump logs.

**Comment by yolocs** [comment]
One solution could be adding a warmup broker that exists until the end of the tests (like in https://github.com/google/knative-gcp/pull/1415). This will make sure the broker data plane is not recycled before we dump the logs.

**Comment by grantr** [comment]
:+1: to adding a warmup broker. Ultimately this workaround can be replaced when we can assign Brokers to multiple BrokerCells in a cluster (see #866).
