### ISSUE TITLE
Figure out what releases to use in an upgrade test and how to find those releases

### ISSUE THREAD

**Issue by ericlem** [google/knative-gcp#1483]
**Problem**
We want to start performing an upgrade test that upgrades from the most recent release to the current head.  As a first step, we need to find a way to find a pointer to the yaml/images for the most recent release to upgrade from.

**Exit Criteria**
A description of what the from and to is, how we find the yaml/images for this release, and a rough description of how we would perform the installation of upgrade.

**Comment by bskaplan** [comment]
Looks like there's a method in knative.dev/eventing/test/e2e-common.sh for finding the latest release from the git tags. Since knative-gcp uses the same release schedule and numbering as knative/eventing, we should be able to re-use that to find the latest release. https://github.com/knative/eventing/blob/master/test/e2e-common.sh#L68

**Comment by bskaplan** [comment]
OK, it's going to be a bit more complicated than that because while we can re-use that implementation for installing upgrades and downgrades to knative-gcp components, we install knative/eventing from the exported YAMLs in GCS. We can either assume knative-gcp versioning matches knative/eventing versioning, or use dates on the GCS objects to find the most recent knative/eventing release for non-release branch runs and the previous knative/eventing release if we're running in a release branch.
