### ISSUE TITLE
Test pubsub client performance in an isolated env

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#1492]
A rough setup could be in a single process having a pubsub client pulls a subscription.
Some variance in the setup:
* Set up the subscription with different `ReceiveSettings`
* Pre-fill the subscription with a lot of messages

Things to look at: cpu/memory usage

**Comment by grantr** [comment]
Proposed exit criteria: a document containing the following:
- A list of scenarios tested
- Explanation of the test setup (so that it can be repeated)
- Results of the tests run
- Analysis of results

Before starting work on this, I'd recommend asking the pubsub client team if they know of any related work we can use.

This issue may be too large for a single sprint.
