### ISSUE TITLE
Determine applicability of Kubernetes QoS classes or priority class to broker deployments

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1502]
**Problem**
Kubernetes supports [QoS classes](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/) and [PriorityClass](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) as methods of controlling which pods should be evicted first under resource pressure. These may be useful when planning the preemption of broker pods vs customer pods.

**Comment by grac3gao** [comment]
For the **QoS**, there are three levels, best-effort, burstable and guaranteed (less important -> more important). When the node is overcommitted, Kubelet will kill containers that are less important: [QoS classes](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/resource-qos.md#qos-classes)

Currently, we set our memory/CPU limit > memory/CPU request, and it is in burstable class. 

According to [OOM Score configuration at the Nodes](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/resource-qos.md#oom-score-configuration-at-the-nodes), once a burstable pod's memory usage exceeds its request (but less than limit), it will have the same OOM Score ( OOM_SCORE = 1000) as best-effort class, and it is easier to be killed.
(CPU usage doesn't affect the score). 

On the production cluster, we may want things to be more stable and predictable, the containers may be mainly guaranteed type and some burstable type[Kubernetes Pattern](https://www.redhat.com/cms/managed-files/cm-oreilly-kubernetes-patterns-ebook-f19824-201910-en.pdf). In this case, setting memory limit == memory request is recommended to avoid pods being easier killed, no matter if CPU limit == CPU request (which is in guaranteed class), or CPU limit > CPU request (which still make the Pod in burstable class)

We might put it into consideration to make broker pod memory limit == memory request (in this case, memory request may be changed to be a higher value than the current one)

**Comment by grac3gao** [comment]
For the **Pod Priority**, it is used for scheduler to order pending pods. ([Effect of Pod priority on scheduling order](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#effect-of-pod-priority-on-scheduling-order)). If no Node is found that satisfies all the specified requirements of the Pod, Preemption logic will preempt lower priority Pods which are in the Node according [Preemption](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#preemption). Detailed order logic are in [Preemption Order](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/pod-preemption.md#preemption-order)

Also, Pod Priority is considered by kubelet to evict Pods together with QoS. [Evicting end-user Pods](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#evicting-end-user-pods)

**Comment by grac3gao** [comment]
For summary, there are three scenarios:
1. [Node OOM Behavior](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#node-oom-behavior):
Referring to when node experiences a system OOM (out of memory) event **prior** to the` kubelet` being able to reclaim memory, `kubelet` will kill some containers as OOM. The difference between Pod eviction and Pod container OOM killed is Pod container may be restarted by `kubelet` based on its `RestartPolicy` when it is OOM killed.
This is purely based on QoS and scoring rule in [OOM Score configuration at the Nodes](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/resource-qos.md#oom-score-configuration-at-the-nodes)
2. [Eviction](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-eviction.md#eviction-strategy): 
Referring to `kubelet` kills one or more Pods in order to reclaim the starved resource. (e.g. when some pods use more memory than its request) [[Configure Out of Resource Handling](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#evicting-end-user-pods)]. 
According to [Evicting end-user Pods](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#evicting-end-user-pods) and [Eviction Strategy](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/kubelet-eviction.md#eviction-strategy), it will target pods that are the lowest Pod Priority, and are the largest consumers of the starved resource relative to their scheduling request. It will target pods whose usage of the starved resource exceeds its requests. Of those pods, it will rank by priority, then usage - requests. 
3. [Preemption](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#interactions-of-pod-priority-and-qos):
Referring to scheduler remove one or more Pods with lower priority in order to schedule a higher priority in the Node. According to [Preemption order](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/pod-preemption.md#preemption-order), the preemption logic mainly consider `Priority` for the Pod, it will consider QoS only when there are equal Priority. And it is importance to note that in most cases, preemption logic will not remove `best effort` Pods, as their request is empty, which is regards as zero.

For current Broker Pods, it is possible to experience one of the scenarios mentioned above:
1. When it will happen: node is overcommitted.
2. Possibility to happen: very common in on-prem clusters where the number of nodes is fixed, but it can similarly happen in cloud as cloud customers may choose to run their clusters overcommitted/overloaded at times in order to save money. (For example, a cloud customer may choose to run at most 100 nodes, knowing that all of their critical workloads fit on 100 nodes and if there is more work, they won’t be critical and can wait until cluster load decreases.) from [Pod Preemption in Kubernetes](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/pod-preemption.md#preemption---eviction-workflow)
3. For Node OOM and Eviction:
    Current Broker Pods set memory request < memory limit, when it consume more memory than its request, it will possibly 
     a) be killed for OOM, as it has a high OOM score.
or b) be killed for eviction, as it uses resource which exceeds its requests and doesn't have a high `Priority`
4. For Preemption:
   Current Broker Pods has the default Priority '0', and is in burstable QoS, as preemption logic doesn't consider best effort Pods, once the broker pods exceeds the memory request, it is easier to be preempted when Node needs to schedule a higher Priority Pod.

Conclusion: 
We might put it into consideration to make broker pod memory limit == memory request (in this case, memory request may be changed to be a higher value than the current one) together with defining a proper `Priority` for the broker pod, in order to avoid the above three corner cases.

**Comment by grac3gao** [comment]
Created follow-up issue #1524 & #1525 based on the summary.
