### ISSUE TITLE
knative trigger status Unknown because TopicReady Unknown

### ISSUE THREAD

**Issue by runzexia** [google/knative-gcp#1583]
**Describe the bug**
I create knative trigger with default broker(MTChannelBasedBroker) & trigger, it seems gcp controller would reconsile it and cause the trigger not ready.

```
Status:
  Conditions:
    Last Transition Time:  2020-08-14T05:47:51Z
    Status:                True
    Type:                  BrokerReady
    Last Transition Time:  2020-08-14T05:47:54Z
    Status:                True
    Type:                  DependencyReady
    Last Transition Time:  2020-08-14T05:48:02Z
    Status:                Unknown
    Type:                  Ready
    Last Transition Time:  2020-08-14T05:47:54Z
    Status:                True
    Type:                  SubscriberResolved
    Last Transition Time:  2020-08-14T05:48:02Z
    Status:                True
    Type:                  SubscriptionReady
    Last Transition Time:  2020-08-14T05:22:03Z
    Status:                Unknown
    Type:                  TopicReady
```

 **Expected behavior**
trigger ready

 **To Reproduce**
Steps to reproduce the behavior.

 **Knative-GCP release version**
knative-gcp v0.16.0
knative-eventing v0.16.1

**Comment by yolocs** [comment]
Hi @runzexia, thanks for reporting the issue!

Just to understand the issue better.

Were you creating MTChannelBasedBroker with Pubsub channel? If that's case, Topic being not ready is going to cause broker not ready.

Or you were creating it with other Channel implementation and ran into this problem?

**Comment by runzexia** [comment]
hi @yolocs, this broker is created by sugar controller. i think it is  MTChannelBasedBroker with InMemoryChannel. 
I guess `Topic Not Ready` because knative-gcp reconcile resource not belong to it.
Trigger Yaml:
```
kubectl get trigger -n dev1 dn-line-aggregation-ng-trigger -o yaml
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  annotations:
    eventing.knative.dev/creator: system:serviceaccount:kube-system:argocd-manager
    eventing.knative.dev/lastModifier: system:serviceaccount:kube-system:argocd-manager
    knative-eventing-injection: enabled
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"eventing.knative.dev/v1","kind":"Trigger","metadata":{"annotations":{"knative-eventing-injection":"enabled"},"labels":{"app":"dn-line-aggregation-ng","argocd.argoproj.io/instance":"eureka-e2e-dev1-eureka-dn-line-aggregation-ng","chart":"dn-line-aggregation-ng","heritage":"Tiller","release":"eureka-e2e-dev1-eureka-dn-line-aggregation-ng"},"name":"dn-line-aggregation-ng-trigger","namespace":"dev1"},"spec":{"broker":"default","subscriber":{"ref":{"apiVersion":"serving.knative.dev/v1","kind":"Service","name":"dn-line-aggregation-ng"}}}}
  creationTimestamp: "2020-08-26T13:05:27Z"
  finalizers:
  - googlecloud
  generation: 1
  labels:
    app: dn-line-aggregation-ng
    argocd.argoproj.io/instance: eureka-e2e-dev1-eureka-dn-line-aggregation-ng
    chart: dn-line-aggregation-ng
    eventing.knative.dev/broker: default
    heritage: Tiller
    release: eureka-e2e-dev1-eureka-dn-line-aggregation-ng
  managedFields:
  - apiVersion: eventing.knative.dev/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:knative-eventing-injection: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
          f:argocd.argoproj.io/instance: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        .: {}
        f:broker: {}
        f:subscriber:
          .: {}
          f:ref:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
    manager: argocd-application-controller
    operation: Update
    time: "2020-08-26T13:05:27Z"
  - apiVersion: eventing.knative.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"googlecloud": {}
      f:status:
        f:observedGeneration: {}
    manager: controller
    operation: Update
    time: "2020-08-26T13:05:35Z"
  - apiVersion: eventing.knative.dev/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions: {}
        f:subscriberUri: {}
    manager: mtchannel_broker
    operation: Update
    time: "2020-08-26T13:05:44Z"
  name: dn-line-aggregation-ng-trigger
  namespace: dev1
  resourceVersion: "38670857"
  selfLink: /apis/eventing.knative.dev/v1/namespaces/dev1/triggers/dn-line-aggregation-ng-trigger
  uid: 01e909cc-86ee-4598-ab1b-a5876f473f91
spec:
  broker: default
  filter: {}
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: dn-line-aggregation-ng
      namespace: dev1
status:
  conditions:
  - lastTransitionTime: "2020-08-26T13:05:31Z"
    status: "True"
    type: BrokerReady
  - lastTransitionTime: "2020-08-26T13:05:31Z"
    status: "True"
    type: DependencyReady
  - lastTransitionTime: "2020-08-26T13:05:39Z"
    status: Unknown
    type: Ready
  - lastTransitionTime: "2020-08-26T13:05:31Z"
    status: "True"
    type: SubscriberResolved
  - lastTransitionTime: "2020-08-26T13:05:43Z"
    status: "True"
    type: SubscriptionReady
  - lastTransitionTime: "2020-08-26T13:05:35Z"
    status: Unknown
    type: TopicReady
  observedGeneration: 1
  subscriberUri: http://dn-line-aggregation-ng.dev1.svc.cluster.local
```

**Comment by yolocs** [comment]
Could you also provide the broker yaml output and two configmaps `default-ch-webhook` and `config-br-default-channel` in the `knative-eventing` namespace? That will help us better understand the problem.

**Comment by runzexia** [comment]
broker :
```
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
    eventing.knative.dev/creator: system:serviceaccount:knative-eventing:eventing-controller
    eventing.knative.dev/lastModifier: system:serviceaccount:knative-eventing:eventing-controller
  creationTimestamp: "2020-08-26T09:01:10Z"
  finalizers:
  - brokers.eventing.knative.dev
  generation: 1
  labels:
    eventing.knative.dev/injected: "true"
  managedFields:
  - apiVersion: eventing.knative.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:eventing.knative.dev/broker.class: {}
        f:labels:
          .: {}
          f:eventing.knative.dev/injected: {}
      f:spec: {}
    manager: sugar_controller
    operation: Update
    time: "2020-08-26T09:01:09Z"
  - apiVersion: eventing.knative.dev/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"brokers.eventing.knative.dev": {}
      f:status:
        .: {}
        f:address:
          .: {}
          f:url: {}
        f:conditions: {}
        f:observedGeneration: {}
    manager: mtchannel_broker
    operation: Update
    time: "2020-08-26T12:52:41Z"
  - apiVersion: eventing.knative.dev/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:annotations:
          .: {}
          f:knative.dev/channelAPIVersion: {}
          f:knative.dev/channelAddress: {}
          f:knative.dev/channelKind: {}
          f:knative.dev/channelName: {}
    manager: mtchannel_broker
    operation: Update
    time: "2020-08-26T12:53:04Z"
  name: default
  namespace: dev1
  resourceVersion: "38647433"
  selfLink: /apis/eventing.knative.dev/v1/namespaces/dev1/brokers/default
  uid: d8d91388-006c-424a-80db-3e9177b94fe5
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: config-br-default-channel
    namespace: knative-eventing
status:
  address:
    url: http://broker-ingress.knative-eventing.svc.cluster.local/dev1/default
  annotations:
    knative.dev/channelAPIVersion: messaging.knative.dev/v1beta1
    knative.dev/channelAddress: http://default-kne-trigger-kn-channel.dev1.svc.cluster.local
    knative.dev/channelKind: InMemoryChannel
    knative.dev/channelName: default-kne-trigger
  conditions:
  - lastTransitionTime: "2020-08-26T09:01:13Z"
    status: "True"
    type: Addressable
  - lastTransitionTime: "2020-08-26T09:01:13Z"
    status: "True"
    type: FilterReady
  - lastTransitionTime: "2020-08-26T09:01:13Z"
    status: "True"
    type: IngressReady
  - lastTransitionTime: "2020-08-26T12:52:41Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2020-08-26T12:52:41Z"
    status: "True"
    type: TriggerChannelReady
  observedGeneration: 1
```

default-ch-webhook
```
apiVersion: v1
data:
  default-ch-config: |
    clusterDefault:
      apiVersion: messaging.knative.dev/v1beta1
      kind: InMemoryChannel
    namespaceDefaults:
      some-namespace:
        apiVersion: messaging.knative.dev/v1beta1
        kind: InMemoryChannel
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"default-ch-config":"clusterDefault:\n  apiVersion: messaging.knative.dev/v1beta1\n  kind: InMemoryChannel\nnamespaceDefaults:\n  some-namespace:\n    apiVersion: messaging.knative.dev/v1beta1\n    kind: InMemoryChannel\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"eventing.knative.dev/release":"v0.16.1"},"name":"default-ch-webhook","namespace":"knative-eventing"}}
  creationTimestamp: "2020-07-30T06:27:00Z"
  labels:
    eventing.knative.dev/release: v0.16.1
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:default-ch-config: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:eventing.knative.dev/release: {}
    manager: kubectl
    operation: Update
    time: "2020-09-03T08:42:00Z"
  name: default-ch-webhook
  namespace: knative-eventing
  resourceVersion: "55528864"
  selfLink: /api/v1/namespaces/knative-eventing/configmaps/default-ch-webhook
  uid: 7a81c652-33e5-4313-a796-cec9f583a20b
```
config-br-default-channel
```
apiVersion: v1
data:
  channelTemplateSpec: |
    apiVersion: messaging.knative.dev/v1beta1
    kind: InMemoryChannel
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"channelTemplateSpec":"apiVersion: messaging.knative.dev/v1beta1\nkind: InMemoryChannel\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"eventing.knative.dev/release":"v0.16.1"},"name":"config-br-default-channel","namespace":"knative-eventing"}}
  creationTimestamp: "2020-07-30T06:26:57Z"
  labels:
    eventing.knative.dev/release: v0.16.1
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:channelTemplateSpec: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:eventing.knative.dev/release: {}
    manager: kubectl
    operation: Update
    time: "2020-09-03T08:41:58Z"
  name: config-br-default-channel
  namespace: knative-eventing
  resourceVersion: "55528807"
  selfLink: /api/v1/namespaces/knative-eventing/configmaps/config-br-default-channel
  uid: e04431e7-c4cc-41fd-869a-ac306c2179e1
```

**Comment by yolocs** [comment]
Thanks @runzexia. We will take a look.

**Comment by cathyzhyi** [comment]
I took the following steps to try to reproduce the issue:

1.  install knative eventing
2. install mt-channel-broker and sugar controller 
3. kubectl create namespace test-tigger
4. kubectl label namespace default knative-eventing-injection=enabled
5. install knative-gcp
6. create a trigger with the following yaml file
```
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: my-trigger
  namespace: test-trigger
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
      namespace: test-trigger
```

In my case, the `my-trigger` does have a `TopicReady` status with value `True`. I think gcp-controller trying to reconcile the topic is because this logic here https://github.com/google/knative-gcp/blob/b872b60742a772117fc3ab5a0394c93633e74d45/pkg/reconciler/trigger/trigger.go#L105-L109  It finalizes the trigger when the broker of the trigger is not gcp-broker. I have 2 questions: 
@runzexia could you describe more detailed instructions to reproduce the issue? My steps to reproduce the problem shows that the topic and trigger are ready. 
@liu-cong do you think what I am seeing when trying to reproduce the failure is expected?

**Comment by yolocs** [comment]
Let me try to add more context. I believe the reason why we finalize non-gcp-broker triggers is that: 1. a trigger is pointing to a **gcp** broker named "x", 2. "x" is now deleted, 3. a new **non-gcp** broker is created with name "x". In this case, we want to GC the pubsub resources we created for the trigger since it's no longer in our control. But we really don't know whether a trigger was ever pointing to a gcp broker before, so we nonetheless finalize all the triggers not pointing a gcp broker. However, if the knative-gcp controller permission is not set up correctly, the finalize will fail which marks TriggerReady=false.

@liu-cong @grantr Since trigger doesn't allow mutating broker ref and it's probably uncommon to recreate the same broker with a different broker class (or we can document it), maybe we should drop this logic so that we don't finalize non-gcp triggers. Thoughts?

**Comment by grantr** [comment]
@yolocs is there any evidence that the `default` broker in these cases was originally the gcp broker class, then switched to MTChannelBasedBroker? Seems like these brokers start as MTChannelBasedBroker.

**Comment by yolocs** [comment]
Yes, they started as MTChannelBasedBroker. But our trigger controller has no way to know whether if they were gcp brokers or not. And we always finalize triggers pointing to non-gcp brokers.

**Comment by liu-cong** [comment]
@yolocs 's theory seems reasonable to me! If auth is setup properly, I think this should not be an issue, and that's probably why @cathyzhyi couldn't reproduce it.

We could skip the logic to finalize triggers pointing to a non GCP broker with dangling retry topic/sub if users do recreate the broker with a different brokerclass.

However, I believe a better fix is #1164. That allows us to add a finalizer to the trigger only when our GCP controller touches it. And we rely on the finalizer to tell whether we should clean up pubsub resources for a trigger.

**Comment by cathyzhyi** [comment]
According to the discussion above, I am going to fix this by not finalizing any trigger pointing to a non GCP broker. I opened a new issue to describe the potential problem can be caused by this fix https://github.com/google/knative-gcp/issues/1687 and will add the limitation into some documentation.

**Comment by liu-cong** [comment]
Instead of skipping the trigger finalizer entirely, I would try to do a best-effort finalizing. However, we would always return success even if we fail to cleanup the pubsub resources.

**Comment by yolocs** [comment]
What @liu-cong suggested sounds reasonable.

**Comment by cathyzhyi** [comment]
The statement in https://github.com/google/knative-gcp/issues/1583#issuecomment-689717174 about FinalizeKind resulting in The `type: TopicReady` is wrong. The trigger status is initialized in `PreProcessReconcile` https://github.com/knative/pkg/blob/a5e2edc217c09add4a3152c2d24930810800e523/reconciler/reconcile_common.go#L42-L55 which is called before `ReconcileKind`. Therefore, the condition `TopicReady` would be initialized no matter the GCP controller finalizes the topic or not.  Because the initial status is set according to the `happy` condition of the old status https://github.com/knative/pkg/blob/a5e2edc217c09add4a3152c2d24930810800e523/apis/condition_set.go#L417-L434. The `TopicReady` can be set to `unknown` or `True` depending on whether the eventing controller has finished reconciling the topic. That's why I can see the problem reproduced intermittently.

**Comment by cathyzhyi** [comment]
with short term fix in https://github.com/google/knative-gcp/pull/1703 the trigger readiness shouldn't be blocked anymore. I opened a new issue https://github.com/google/knative-gcp/issues/1687  to describe the potential problems with the short term fix.

If the broker has been deleted, I choose to leave the code as it is now for the following reasons: 1. users of GCP brokers can delete the broker normally and observe any potential errors normally.  2. users of GCP broker can observe confusing `TopicReady:unknown/True` but it shouldn't affect their experience since the broker is deleted already. 

If the broker is recreated or just created from scratch with  non GCP broker, I choose to do best effort finalizing the trigger and always mark `TopicReady: True` as suggested by @liu-cong
