### ISSUE TITLE
Adjust broker retry resource requirements to meet default retry attempts per second target

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1602]
**Problem**
Once we have a retry attempts per second target #1598 and a default event payload size #1599, we can measure the resource requirements for a single retry pod to meet the target. That's our default resource requirement value.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
User

**Exit Criteria**
The broker retry deployment is created with default resource requirements allowing it to meet the default retry attempts per second target.

**Additional context (optional)**
Part of #1552.

**Comment by grantr** [comment]
#970 is effectively a subtask of this one.

**Comment by cathyzhyi** [comment]
here are the configuration proposed to reach the target throughput in #1598 
* **CPU**
    * **Request:** 2000m 
This is based on all the experiments did with different combinations (`rps`* `payload size` *`number of triggers` ) to reach target throughput. The highest CPU consumption for a single pod is around 3500-4000m. With autoscaling, this is set to a lower number so that a single pod resources requirement won't be too high. 
* **Memory** 
    * **Limit** == **request**: 2 Gb 
     This is to protect the retry from OOM when **MaxOutStandingMessages** is set to 100. With 100 trigger * 256kb payload size when reaching the target throughput or a little bit higher, memory request lower than 2G, 1 or 1.5G for example, would result in OOM. Memory request of 2G is quite stable even when dealing with throughput higher than the default target. The reason for setting **MaxOutStandingMessages**  is stated in the **Pubsub receiveSetting**  part. 
* **Autoscaling params** 
    * **CPU utilization threshold:** 95% 
   The rationale behind this number is mainly for good CPU utilization. Setting it relatively high so that retry doesn't scale out too fast and end up using only part of the requested CPU.
    * **Memory consumption threshold:** 1000Mi 
        * This number is set well below the request to add safety buffer in case of memory surge. In reality, it's very unlikely this value triggers auto scaling because the CPU threshold is usually reached before memory. 

* **Pubsub receiveSetting** 
    * **OutstandingMessages on ReceiverSettings**: 100 (unchanged)
    Both setting _MaxOutstandingMessags=10, memory limit=1G_ or _MaxOutstandingMessags=100, memory limit=2G_  can protect retry from OOM with 256k payload * 100 trigger with very high inbound traffic. The second setting is chosen because: 1. the first setting can compromise throughput for smaller payload  2. the target throughput can be reached with most of the combinations already and a higher value would not be necessary and can end up with higher memory request. 
    * **OutstandingBytes in ReceiveSettings**: reading [pubsub source code](https://github.com/googleapis/google-cloud-go/blob/26c4a53b2150dc3cfd2e1bb09840072346039aa5/pubsub/subscription.go ) seems this number is only used for asynchronous pull.
