### ISSUE TITLE
Observed brokercell pod update rate of 40/s

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1611]
**Describe the bug**
A GKE investigation identified some dev-owned GKE clusters that are updating brokercell-fanout, brokercell-ingress, and brokercell-retry pods 40 times per second. Whether this is steady state update or peak, it's very likely to be a bug in the brokercell controller somewhere. I can't think of a reason to be updating pods 40 times in a second.

Probably it's related to the annotation update code that forces the configmap volume refresh.

 **Expected behavior**
Brokercell pods are updated a few times per second, only when the configmap content changes.

 **To Reproduce**
Unknown

 **Knative-GCP release version**
Unknown

 **Additional context**
This may be related to #1593.

**Comment by tommyreddad** [comment]
How to reproduce: create many brokers. The brokercell pod update rate will scale rapidly with the number of existing brokers, and does not stop. To see this happen clearly, just create 50 brokers and observe the brokercell pod volumeGeneration rapidly climb to 1000.

This is caused by a bug in the broker-targets ConfigMap diff check in the [DeepEquals](https://github.com/google/knative-gcp/blob/master/pkg/reconciler/utils/configmap.go#L61), which fails since the broker-targets ConfigMap's BinaryData is a serialized proto, and [protos should be compared with proto.Equals](https://developers.google.com/protocol-buffers/docs/reference/go/faq#deepequal). So, due to the bug, identical ConfigMap BinaryData will be reported as unequal. PR incoming.
