### ISSUE TITLE
Missing `google-broker-key` secret in `dataplane-service-account.md`

### ISSUE THREAD

**Issue by zhongduo** [google/knative-gcp#1623]
**Describe the bug**
The existing `dataplane-service-account.md` does not create a `google-broker-key` secret, this will result in `Failed to publish to PubSub` error when sending events to the gcp broker. 

 **Expected behavior**
The secret key `google-broker-key` gets created in the documentation.

 **To Reproduce**
With a fresh GKE cluster, follow the instructions in: https://github.com/google/knative-gcp/tree/master/docs/examples/gcpbroker

 **Knative-GCP release version**

 **Additional context**

**Comment by danyinggu** [comment]
In https://github.com/google/knative-gcp/tree/master/docs/examples/gcpbroker, it is actually pointing to https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md in the [prerequisites](https://github.com/google/knative-gcp/tree/master/docs/examples/gcpbroker#prerequisites) section, so I think there is not a bug in the current documentation.

Also, as @grac3gao mentioned in the standup, the dataplane service account and broker service account are separate concepts. The dataplane GSA are for sources, while the broker service account is for broker. In the example, we are using the same service account because currently they need the same role. So I think it would make more sense if we separate broker service account set up with dataplane service account set up guide.

**Comment by zhongduo** [comment]
> In https://github.com/google/knative-gcp/tree/master/docs/examples/gcpbroker, it is actually pointing to https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md in the [prerequisites](https://github.com/google/knative-gcp/tree/master/docs/examples/gcpbroker#prerequisites) section, so this is not a bug in the current documentation.
> 
> Also, as @grac3gao mentioned in the standup, the dataplane service account and broker service account are separate concepts. The dataplane GSA is for source dataplane, while the broker service account is for broker dataplane. In the example, we are using the same service account because currently they need the same role, but they are actually creating different secret under different namespace. So I think it would make more sense if we separate broker service account set up with dataplane service account set up guide.

Agreed it is not a bug in the gcpbroker doc, but it is a bug now in https://github.com/google/knative-gcp/tree/master/docs/examples/metrics which was what I followed originally before it was merged. I think the action item in this issue is to avoid duplication of the section `How to add google-broker-key` in different docs, otherwise it will be very easy to have this problem again in a new doc.

**Comment by grac3gao** [comment]
From my point of view, [Metrics Example]( https://github.com/google/knative-gcp/tree/master/docs/examples/metrics ) Prerequisites (2) should point to [Installing GCP Broker](https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md)(it only need broker, doesn't need any sources). [Installing GCP Broker](https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md) Prerequisites (2) should directly point the specific section https://github.com/google/knative-gcp/blob/master/docs/install/dataplane-service-account.md#create-a-google-cloud-service-account-to-interact-with-pubsub, instead of the head of the doc https://github.com/google/knative-gcp/blob/master/docs/install/dataplane-service-account.md. This would make things consistent.

**Comment by danyinggu** [comment]
> From my point of view, [Metrics Example](https://github.com/google/knative-gcp/tree/master/docs/examples/metrics) Prerequisites (2) should point to [Installing GCP Broker](https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md)(it only need broker, doesn't need any sources). [Installing GCP Broker](https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md) Prerequisites (2) should directly point the specific section https://github.com/google/knative-gcp/blob/master/docs/install/dataplane-service-account.md#create-a-google-cloud-service-account-to-interact-with-pubsub, instead of the head of the doc https://github.com/google/knative-gcp/blob/master/docs/install/dataplane-service-account.md. This would make things consistent.

I agree. This makes sense.

**Comment by zhongduo** [comment]
> From my point of view, [Metrics Example](https://github.com/google/knative-gcp/tree/master/docs/examples/metrics) Prerequisites (2) should point to [Installing GCP Broker](https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md)(it only need broker, doesn't need any sources). [Installing GCP Broker](https://github.com/google/knative-gcp/blob/master/docs/install/install-gcp-broker.md) Prerequisites (2) should directly point the specific section https://github.com/google/knative-gcp/blob/master/docs/install/dataplane-service-account.md#create-a-google-cloud-service-account-to-interact-with-pubsub, instead of the head of the doc https://github.com/google/knative-gcp/blob/master/docs/install/dataplane-service-account.md. This would make things consistent.

That's a good idea, but would you say it is possible to have a doc that only need to set up the `google-broker-key` without needing to apply the broker? If so, I think having a separate doc for setting service account for broker still make sense. Otherwise you can always just use the whole `Install GCP Broker` as a whole as prerequisites.

**Comment by grac3gao** [comment]
The authentication steps for broker and source in those two docs have difference. For secret, they have different namespace and secret name (secret name is kind of fixed in the related Pod volume) and for WI, they have different scenarios. Source examples don’t need broker, broker examples and metric examples don’t need source. I guess that's why we separate them into two different places.

I have an ongoing plan to simplify the setup process (which is based on https://github.com/google/knative-gcp/issues/1496). The main idea is to replace all manual setups with Idempotence scripts. 

Just as the same as we did for control plane setup in https://github.com/google/knative-gcp/blob/master/docs/install/install-knative-gcp.md, all manual configuration steps (secret and WI) will be added in https://github.com/google/knative-gcp/blob/master/docs/install/authentication-mechanisms-gcp.md.  (developers who want to learn detailed configuration steps can refer to this doc and the script, developers who just want to try examples can use scripts). The troubleshooting part in authentication mechanisms will then be moved to a separate doc which will be referred by every examples for debugging purpose.

If this looks good for you, maybe we can just change the link to point to the right doc first, and then consider reducing duplication after those scripts are in place.
