### ISSUE TITLE
Enforce proper commit message to improve the code base

### ISSUE THREAD

**Issue by zhongduo** [google/knative-gcp#1774]
Our existing codebase does not enforce any commit message check hook and also squash happens automatically. This has resulted in very difficult to read commit history, which is supposed to be a informative document of the code change over time. Here is my proposal to improve our code base:

* Enforce commit history check from www.conventionalcommits.org, some of the google cloud repos are already using it.
* Disable auto squash, this will allow user to squash one PR into several meaningful commits, each of which will have proper commit messages.
* Commit message format (not the details of the content) is part of the review process, eg a wrong name of the features.

Here is an example of our commit history:

![image](https://user-images.githubusercontent.com/9036084/94454687-2bf74880-0180-11eb-98aa-353c5bbbb14c.png)

When the commit history check is enforced, here is an example of what it will look like:

![image](https://user-images.githubusercontent.com/9036084/94454839-61039b00-0180-11eb-8c26-694223390b46.png)

**Comment by grantr** [comment]
I agree good commit messages are important and useful when trying to find out why code was written a certain way! But before adding enforcement of commit messages, let's work on the shared understanding of what a good commit message looks like. Once we have that shared understanding, then we can add automatic enforcement if we feel it's useful.

The collaborators in this repo frequently work with Knative and Gerrit repos, both of which use squash. IMO changing the merge method in this repo would require near-universal agreement among collaborators and a clear benefit to the additional cognitive load of a different process going forward. While I personally prefer to split my commits into small chunks and merge instead of squash, there are plenty of voices that prefer the opposite, so I don't think we're going to reach that threshold.

I'm closing this issue for now since I don't think we're ready to add commit message enforcement. I hope we can work on the shared understanding of good commit messages though!
