### ISSUE TITLE
Default broker resource requirements too high for development clusters

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1812]
**Problem**
The BrokerCell default resource requirements are currently intended for production clusters, requesting several CPUs and a few gigabytes of memory. #1671 suggests these requirements are too high for development purposes.

We may want to ship a more development-oriented configuration by default, on the assumption that most installs from this repo will not be running in production immediately. We can document or release separately a BrokerCell configuration that is intended for production.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
User

**Exit Criteria**
The default BrokerCell configuration is functional in a resource-constrained development environment.

**Comment by grantr** [comment]
@upodroid do you have any thoughts on what resources are available in a typical development environment? What tweaks did you make to the BrokerCell resource for #1671?

**Comment by upodroid** [comment]
In a dev environment, you usually run out of cores before memory. In my case I was running a gke cluster with 2 e2-standard-4 nodes with a total of 8 codes. It was running istio + knative + knative-gcp + prom-operator stack.


When I'm creating the broker, I would like to specify the resource limits there so that I don't have to edit the underlying resource such as the brokercell. The deployments that it creates such as the ingress, retry and the fanout can't be edited as the controller reconciles the changes immediately so you need to edit the broker cell resource. 

In terms of the change, I set the CPU request to 100m and the limit to like 2000m. K8s cares about the requests more than the limits. In my cluster, both of them were not using much resources at all.

**Comment by upodroid** [comment]
The default node pool that Google creates nowadays is like 3x e2-medium which is a total of 3 real cores. For some reason k8s doesn't consider it as 6 vcpus
