### ISSUE TITLE
Figure out if we need knative/eventing#4296

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#1835]
https://github.com/knative/eventing/pull/4296 changes the way trigger dependencies are tracked by switching from the kresource duck to the source duck. Do we need this change too?

**Comment by Ectelion** [comment]
The Eventing's construct for tracking trigger dependencies was inherited by the [trigger reconciler](https://github.com/google/knative-gcp/blob/master/pkg/reconciler/trigger/trigger.go) in knative-gcp repo. Thus, we may see the same mismatch between the informer and lister in [pkg/reconciler/trigger/trigger](https://github.com/google/knative-gcp/blob/master/pkg/reconciler/trigger/trigger.go), [pkg/reconciler/trigger/controller](https://github.com/google/knative-gcp/blob/master/pkg/reconciler/trigger/controller.go) and related components.

On the other hand, in case of Knative-GCP, TestGrid results had no indication of flakiness for the relevant TestTriggerDependencyAnnotation test (at least for the available last few weeks). Note that in [the PR addressing knative/eventing#4296](https://github.com/knative/eventing/pull/4296), there appear to be two distinct fixes: one for the discussed informer/lister issue and the other had to do with a broker->trigger typo (see [_checkDependencyAnnotation_](https://github.com/knative/eventing/pull/4296/files#diff-a5e8f7450622c643c47dba67f228062f86e159ce9a79b689d0e4a5f4984aff01) function). It is unclear whether the test failures in the Eventing repo rather had to do with the latter problem, which is non-existent in the knative-gcp's [trigger implementation](https://github.com/google/knative-gcp/blob/df0ee9b094c7885a98edf9d93f15dc60eafaa561/pkg/reconciler/trigger/trigger.go#L356). This may also have to do with the different test environments.

Regardless of test flakiness results, addressing the informer/lister mismatch, [as suggested in knative/eventing/pull/4296](https://github.com/knative/eventing/pull/4296#issuecomment-708257759) and keeping the dependency tracking logic consistent with the Eventing implementation seems to make sense. Relevant PR is sent.

**Comment by Ectelion** [comment]
Also, in case you wonder why the previous version still worked. There are two pieces here: Informer and Lister. When it comes to listing, the difference is in KSources and Sources are ducks, which are very similar/substitutable ones, so listing should work consistently in both cases. Informer is more tricky and my understanding is that it did work before because the Informer events in both cases are inter-related, i.e. a source change and a condition change tend to co-occur with very close timing, but are not quite guaranteed to be always consistent with a different lister.

**Comment by grantr** [comment]
Thanks @Ectelion for investigating and fixing this!
