### ISSUE TITLE
E2E test for the storage source/importer

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#205]
We need an E2E for the storage source/importer. It will have to do the proper cluster setup (e.g., creating secrets, a bucket, etc.), then upload a file, and see that a notification is received on the sink.

There is a working example with PullSubscription, where we might be able to reuse some of the code. Need to sync with @n3wscott

**Comment by nachocano** [comment]
Grace will help with this one after a tracing issue that she is currently working on.
/assign @grac3gao

**Comment by nachocano** [comment]
fyi @vaikas-google @n3wscott

**Comment by vaikas-google** [comment]
so this should basically start out as:
 - create [or have a pre-made bucket for test purposes?]
 - create a service that listens for notifications
 - create Storage object pointing to bucket and to the service above
 - add an object to the Bucket
 - verify results

I think if we use a premade bucket with some credentials that have been properly configured it will be easier rather than create the bucket and grant the necessary permissions.

**Comment by nachocano** [comment]
> I think if we use a premade bucket with some credentials that have been properly configured it will be easier rather than create the bucket and grant the necessary permissions.

Agree!
