### ISSUE TITLE
Controller should watch for changes on its secret

### ISSUE THREAD

**Issue by nachocano** [google/knative-gcp#500]
**Problem**
The controller should watch for patches of its secret, and "update" it accordingly.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Contributor

**Exit Criteria**
Whenever the controller secret is patched, we should be notified so that the Controller is able to read it again 

**Time Estimate (optional):** 
1d

**Additional context (optional)**
Needed for initialization purposes

**Comment by capri-xiyue** [comment]
I added a secret informer for controller. But it doesn't decrease the time needed for sources to reconcile successfully when valid secret gets patched. When the secret informer got added, it really trigger reconciliation when secret gets updated, but the secret got mounted with the pod is still out-dated, therefore the reconciliation still fails. The delay regarding secret update is about 1 min.

Based on the https://kubernetes.io/docs/concepts/configuration/secret/(https://kubernetes.io/docs/concepts/configuration/secret/, 

 **When a secret being already consumed in a volume is updated, projected keys are eventually updated as well. Kubelet is checking whether the mounted secret is fresh on every periodic sync. However, it is using its local cache for getting the current value of the Secret. The type of the cache is configurable using the (ConfigMapAndSecretChangeDetectionStrategy field in KubeletConfiguration struct). It can be either propagated via watch (default), ttl-based, or simply redirecting all requests to directly kube-apiserver. As a result, the total delay from the moment when the Secret is updated to the moment when new keys are projected to the Pod can be as long as kubelet sync period + cache propagation delay, where cache propagation delay depends on the chosen cache type (it equals to watch propagation delay, ttl of cache, or zero corespondingly).**

I checked the default cache type is watch and the default kubelet sync period is 1min. 
Based on this issue https://github.com/kubernetes/kubernetes/issues/30189, 

 kubelet stopped syncing all pods frequently (10s) and unconditionally since v1.2, because of the serious overhead which became increasingly evident as the pod density on the node grew. Pod syncing is now triggered mainly by:
- pod spec changes
- container state changes
- A long, fallback resync interval (--sync-frequency) defaulted to 1 minute
You could increase the resync interval, but be warned that it has the adverse effect of performance overhead if there are many pods on your node. As the issue suggests, kubelet should detect the config map changes another way.

It's not ideal to change the kubelet sync interval since it will bring serious overhead. Need to check whether change the pod sec or container state to force a refresh.

**Comment by capri-xiyue** [comment]
Did some manual test. It works when I updated the annotation of the pod spec of deployments, deployments will recreate the pods which will pick up the latest secret volume(similar to restarting pod). Discussed with @nachocano, it looks like we will need our own deployment controller and reconciler which watch the google-cloud-key secret and then update the controller pod in cloud-run-events with new annotation when secret changes gets detected. But this seems kind of hacky... and probably we shouldn't do it.
