### ISSUE TITLE
Broker ingress available during upgrade

### ISSUE THREAD

**Issue by ericlem** [google/knative-gcp#611]
**Problem**
We want to ensure that all services in the ingress path of the broker can be upgraded through a rolling upgrade or activator model and not experience failures during upgrade.

**Exit Criteria**
Ingress path components are deployed in a way that future upgrades past the version in which this task's output has been deployed can be rolling upgraded or proxied via an activator, preventing unavailability or error returns during upgrade.  

A procedure for deploying an upgrade of these components without unavailability has been documented.

It should pass the tests developed here:
https://github.com/google/knative-gcp/issues/610

**Time Estimate (optional):** 
5d

**Comment by grantr** [comment]
We should be able to use the sendtracker to determine the percentage of requests that were published successfully.
How do we determine the previous and next releases?
What is the load during upgrade?
We may need to adjust rolling update configuration of the deployment.

**Comment by yolocs** [comment]
Test strategy:

- Send events to broker with a steady rate
- Make a change that will cause the controller + brokercell deployments to be updated (to mimic an upgrade)
- Wait a bit longer 
- Watch event reject rate, broker/trigger event count metrics

Results:

Under a fair rps that can be handled by a single pod (<=1000), the upgrade only caused neglectable ingress failures (<1%). Occasionally, the error was 503. In most cases, the error was something like `dial tcp 10.0.56.158:80: connect: no route to host`. In my understanding (**correct me if I'm wrong**), the error seems to be "a moment ago the pod was still alive and its IP was resolved from the ingress address, but when attempting to connect to it the pod was terminated and thus no route". If this is really the case, this is more or less a client side issue and it doesn't indicate our broker is not available.

![83SHNtWHvPAJB3x (1)](https://user-images.githubusercontent.com/14087829/92659057-7e91c300-f2ac-11ea-8de7-32a7136cda1c.png)

When the load was increased until autoscaling is triggered, there was an increased _amount_ of the same error "connect: no route to host". This is somehow expected because with increased concurrency, there is a higher chance more requests will get a previously valid IP.

However there is another problem.

![3ZCPCwXHymhJ7mK](https://user-images.githubusercontent.com/14087829/92659255-df210000-f2ac-11ea-97a1-e2ea38973151.png)

E.g. In the second part of the chart above, before upgrade there were 3 ingress replicas running. When upgrade was happening, brokercell controller will update the deployments but with 1 replica. Shortly after HPA still got to update the replica number back to 3 _but_ for a short period (from several to dozens of seconds) the replica number was reset to 1. During this short period, all the requests were sent to a single pod which obviously was not able to handle such load, and thus other errors showed up. In the test there was 500s caused by pubsub publish buffer limit. This is a problem for upgrade.

**Comment by yolocs** [comment]
> Test strategy:
> 
> * Send events to broker with a steady rate
> * Make a change that will cause the controller + brokercell deployments to be updated (to mimic an upgrade)
> * Wait a bit longer
> * Watch event reject rate, broker/trigger event count metrics
> 
> Results:
> 
> Under a fair rps that can be handled by a single pod (<=1000), the upgrade only caused neglectable ingress failures (<1%). Occasionally, the error was 503. In most cases, the error was something like `dial tcp 10.0.56.158:80: connect: no route to host`. In my understanding (**correct me if I'm wrong**), the error seems to be "a moment ago the pod was still alive and its IP was resolved from the ingress address, but when attempting to connect to it the pod was terminated and thus no route". If this is really the case, this is more or less a client side issue and it doesn't indicate our broker is not available.
> 
> ![83SHNtWHvPAJB3x (1)](https://user-images.githubusercontent.com/14087829/92659057-7e91c300-f2ac-11ea-8de7-32a7136cda1c.png)
> 
> When the load was increased until autoscaling is triggered, there was an increased _amount_ of the same error "connect: no route to host". This is somehow expected because with increased concurrency, there is a higher chance more requests will get a previously valid IP.
> 
> However there is another problem.
> 
> ![3ZCPCwXHymhJ7mK](https://user-images.githubusercontent.com/14087829/92659255-df210000-f2ac-11ea-97a1-e2ea38973151.png)
> 
> E.g. In the second part of the chart above, before upgrade there were 3 ingress replicas running. When upgrade was happening, brokercell controller will update the deployments but with 1 replica. Shortly after HPA still got to update the replica number back to 3 _but_ for a short period (from several to dozens of seconds) the replica number was reset to 1. During this short period, all the requests were sent to a single pod which obviously was not able to handle such load, and thus other errors showed up. In the test there was 500s caused by pubsub publish buffer limit. This is a problem for upgrade.

**Comment by yolocs** [comment]
Tested brokercell reconciliation without updating replicas. The dip caused by error "connect: no route to host" still exists but there was no more surge of 500s as shown above.

![9nS4qogVA7qYvFY](https://user-images.githubusercontent.com/14087829/92786731-58782b80-f35d-11ea-8834-b0bbfc76574b.png)

Created issue: https://github.com/google/knative-gcp/issues/1683

**Comment by yolocs** [comment]
My early [understanding](https://github.com/google/knative-gcp/issues/611#issuecomment-689850159) of "connect: no route to host" errors was wrong. It's not client side errors. What happened is that a request reached the ingress service but the service didn't find a backing pod to handle the request. Why that happened is still unclear. A potential cause is that kube proxy needs a second to resync IP table to add the new route for the new pods. However, it hard to believe we're the first one see such issues.

In several follow-up tests, I found that adding `spec.MinReadySeconds = 60s` could effectively counter such errors. With a steady 4500 rps load, requests rejected by the ingress during upgrade was mostly single digit. Consider a 5s time window, the availability was for sure way above 99.99%.

Although `spec.MinReadySeconds = 60s` is the main contributor that reduced errors during upgrade, I propose several other changes. Here is the list.

1. `spec.MinReadySeconds = 60s` for all broker deployments. It not only helps ingress during upgrade, it also give fanout/retry some warm up time as posted in this [article](https://www.bluematador.com/blog/kubernetes-deployments-rolling-update-configuration#:~:text=Kubernetes%20Rolling%20Updates,-One%20of%20the&text=Rolling%20updates%20allow%20you%20to,strategy.).
2. Set the following rolling update strategy. This is probably the safest strategy to make sure upgrade doesn't cause a change in the broker capacity.

```
			Strategy: appsv1.DeploymentStrategy{
				RollingUpdate: &appsv1.RollingUpdateDeployment{
					MaxSurge:       &intstr.IntOrString{IntVal: 1},
					MaxUnavailable: &intstr.IntOrString{IntVal: 0},
				},
			},  
```
3. Extend `PeriodSeconds` to `15s` in probes. Under heavy load it helps reduce some noise.
