### ISSUE TITLE
Scale Broker fanout/retry

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#642]
Scale up and down as needed to handle **consumer throughput**. If consumers are unavailable, no need to scale up regardless of queue length.

If namespaced, must scale to zero. if cluster-wide, can scale to 1.

/area broker

**Comment by grantr** [comment]
(Let's imagine that KEDA is rock-solid stable today and uses metrics that react quickly to queue length changes, or we have a similar system that can scale quickly based on queue length of a pubsub topic. None of this is true today, but ignore that)

With a cluster-wide deployment, scaling to zero isn't critical, but scaling to N is. For 1-N scaling, KEDA uses HPA to scale a deployment on queue length as a custom metric. This works for scaling stateless consumers because **queue length and consumer scale are directly related**. More consumers equals more throughput which means queue length goes down which ultimately scales consumers back down.

It's not clear to me how this method can accurately scale intermediaries like the fanout service because **scaling the fanout service does not directly affect the queue length**. Only scaling the consumer can change the queue length. Scaling the fanout service up is a waste of resources if the consumer has not also scaled up its throughput.

Can we describe how we plan to use KEDA, or any queue-length based scaler to scale the fanout service?

(retry service is similar, but let's focus on fanout service for now)

**Comment by ericlem** [comment]
Assuming consumers can scale, queue length is related to the fanout service scale.  As consumers are backing up the scaling policies on the consumers should be increasing as well so that the consumer horizontally scales to take more load.  I'll agree if consumers don't, that becomes a problem.  Presumably that eventually shows up as increasing consumer latency and causes us to start forwarding their traffic to the resend queue if they aren't scaling properly (protecting other consumers).  And yes, that begs the question how to scale the resend queue.

**Comment by liu-cong** [comment]
Since we don't have knowledge on whether the consumer can scale, can we use some heuristics that takes into account the decouple queue length, resend queue length, and potentially other metrics such as consumer latency?

Also, is there some sort of "feedback" mechanism in KEDA? I think the ultimate goal of scaling fanout service is to increase egress throughput. If we can stop scaling if throughput is not improved, that will be great.

**Comment by grantr** [comment]
KEDA doesn't have a feedback mechanism that I'm aware of. Its implementation of 1->N scaling is an HPA set to [scale on a custom metric](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-custom-metrics) that reports queue length. So if we used KEDA as currently implemented to scale, we would not be able to use negative feedback based on consumer throughput.

**Comment by ericlem** [comment]
My gut feeling is that we don't want to scale back based on consumer throughput (for some range of queue length timescale measumerent)...  We'll want to start queueing on resend queues at that point.  And yes, you can bring that question back up there.  We want the decoupling queue to keep up as much as possible assuming we have more than one consumer.

**Comment by liu-cong** [comment]
> We want the decoupling queue to keep up as much as possible assuming we have more than one consumer.

Agree. 

What's our strategy to scale the retry service? Or is it not important at this point?

**Comment by yolocs** [comment]
From the offline discussion, the conclusion seems to be: there is no single metric we can rely on to scale fanout properly; instead, we need to look at a combination of metrics including ingress load (qps), queue length, fanout resource usage (cpu + memory), downstream response (response code, timeouts).

Giving each metric a weight, with some algorithm we can calculate and combine them into a single metric - naively would be something like `M = Max(qps*w1, len*w2, usage*w3, resp*w4)`. If we feed this metric to HPA as a custom metric, theoretically it could work. Similar thing could be applied to retry as well.

Thoughts?

**Comment by grantr** [comment]
If we ultimately have to aggregate multiple metrics, then it seems reasonable to sum the lengths of all relevant topics to produce a single aggregate length.

**Comment by ericlem** [comment]
@grantr I think it's a reasonable first approximation.  We may need some form of exception to exclude queues that haven't shrunken at all in some amount of time (ie, queues that are growing because the consumer isn't consuming at all.)

**Comment by ericlem** [comment]
That last comment only apply to the retry queues though.

**Comment by ericlem** [comment]
@Harwayne

**Comment by grantr** [comment]
Fixed by #1107
