### ISSUE TITLE
Decoupling topic: per broker or per data plane

### ISSUE THREAD

**Issue by grantr** [google/knative-gcp#699]
**Problem**
We can have one decoupling topic per broker (similar to the current architecture) or one decoupling topic per data plane "cell" (by default, one for all brokers in the cluster). If the topic is shared by several brokers, we need a way to partition the messages as discussed in #667.

I'd like to document a decision on this and the rationale for that decision.

**Comment by grantr** [comment]
My thoughts:
1. Topic per-broker gives us a natural partitioning scheme without needing to embed that in the message. Additional topics don't cost more.
1. Control plane already has to manage a topic per trigger, likely to be more than the number of brokers, so managing a topic per broker doesn't seem like much extra work.
1. Conversely, having the broker controller manage a single topic that is unconnected to any specific resource seems odd. In this scenario, allowing the Topic and PullSub resources to be control-plane only without receive adapters as proposed in #690 seems like the right approach, since it can be created at install time alongside the data plane deployments (presumably also created by install yaml).
1. Shared topic _maybe_ gives us the ability to broadcast one message from a source to many brokers, but it's vague to me how this would work or even if we want it.
1. Shared topic might make fanout service easier to scale, but we need to solve the multi-topic scaling problem anyway for retry service.

**Comment by ericlem** [comment]
-Reasons for a single topic:
-   Makes scaling for the main puller more straightforward (watch a single pub sub channel), only one pool of pullers for pub sub
-   Makes the controller for creating/destroying a broker slightly easier (no channel and subscription create/destroy)
-   Obvious extension for globally available events (ie, events sent once, received by all brokers)
- Reasons against one channel
-   Fewer knobs for isolating brokers from each other
-   don't need metadata attached to cloudevents

**Comment by yolocs** [comment]
> 5. Shared topic might make fanout service easier to scale, but we need to solve the multi-topic scaling problem anyway for retry service.

Properly scaling the happy path is probably more important. For retry, we can probably live with longer delay which gives us some flexibility on how to design scaling.

**Comment by liu-cong** [comment]
> Fewer knobs for isolating brokers from each other

I'd like to vote on this point. For example, It's easier to rate limit the fanout for a broker with multiple topics for the "noisy neighbor" problem. 
The partitioning scheme is a nice-to-have feature but it can be relatively easily solved by labelling events.

**Comment by grantr** [comment]
> Makes scaling for the main puller more straightforward (watch a single pub sub channel)

Can we talk more about scaling? It's not clear to me how this would work or why it would be straightforward, and I think it's important to get concrete now since we're making design choices based on perceived ease of implementation. I added my thoughts to #642, please add yours too. :smiley:

**Comment by grantr** [comment]
(continuation of above)
If we don't have a clear design in our heads of how to scale based on pubsub metrics (#642), then I don't think we can say with confidence that scaling is more straightforward with a single topic than multiple topics.

> Makes the controller for creating/destroying a broker slightly easier (no channel and subscription create/destroy)

I'll push back on this a bit. The controller is already dealing with many of these objects for triggers. The topic and pullsubscription must be created by something, whether it's code or yaml or the user, so their lifecycle complexity is still there. If we're making the broker controller easier to write, then what's getting more complex?

**Comment by ericlem** [comment]
Simply having to do anything other than creating or destroying

**Comment by ericlem** [comment]
> (continuation of above)
> If we don't have a clear design in our heads of how to scale based on pubsub metrics (#642), then I don't think we can say with confidence that scaling is more straightforward with a single topic than multiple topics.
> 

I'd be hard pressed to come up with a scaling strategy for pulling off a queue that is harder when pulling off a single pub sub topic then pulling off multiple topics.  Fairness is a different point, but the simple pub sub topic pull scaling is almost certainlly at least as easy in this case (one set of pull threads, rather than having x threads pulling from topic a, y threads pulling from topic b, and we have to scale based on the queue length of three queues, etc.  I'll agree that the question of how much easier isn't clear yet, but it's hard to think that it seems extremely likely to be at least slightly easier.

> > Makes the controller for creating/destroying a broker slightly easier (no channel and subscription create/destroy)
> 
> I'll push back on this a bit. The controller is already dealing with many of these objects for triggers. The topic and pullsubscription must be created by something, whether it's code or yaml or the user, so their lifecycle complexity is still there. If we're making the broker controller easier to write, then what's getting more complex?

You now have to make a topic/pull subscription and delete a topic/pull subscription each time you create or destroy a broker.  It's not rocket science more difficult, but it is an extra step.  Previously the only lifetime issue on those was initial creation.  The only deletion (if we did any at all) would effectively be at cluster teardown time.

**Comment by yolocs** [comment]
I don't think "isolation" is a top priority in this shared data-plane approach. If lack of isolation is a problem, I think the right solution is to **also** support data-plane in user namespace mode.

With that said, if we can label events, the other extreme would be to have a shared retry topic and a shared retry subscription. We can label events so that when an event is pulled from the retry subscription, we know where to send (retry) it. This way we could drop all the dynamic retry topic/subscription provisioning and simply provide two topics/subscriptions for the broker. The scaling of the retry service would also be similar to fanout. How does that sound?

**Comment by grantr** [comment]
> the other extreme would be to have a shared retry topic and a shared retry subscription.

There are two options for this and I'm not sure which you're proposing:

1. Send each event to the retry topic once per undelivered trigger (N events)
1. Send each event to the retry topic once for all undelivered triggers (1 event)

**Comment by yolocs** [comment]
> There are two options for this and I'm not sure which you're proposing:

I meant #1. I think the cost would be same as having N retry queues.

**Comment by grantr** [comment]
My concern with that approach is that when the event comes out of the retry queue needing to be delivered to 2 subscribers, and only 1 acks, then we need to re-enqueue that event to update its retry state. The event then goes to the back of the queue and waits for every other retry to be processed before it can come back around to be retried. This makes the retry timing more unpredictable. If a single consumer is offline and matching incoming events, the retry queue for everyone will get longer and longer, but we still want to quickly retry events for other consumers. I'm not sure how we handle that situation.

**Comment by yolocs** [comment]
@grantr 

> My concern with that approach is that when the event comes out of the retry queue needing to be delivered to 2 subscribers, and only 1 acks

This shouldn't happen. Here is a flow in my mind:

```
                      / Target1 (failed) \                    / Target1 (success - ack E1) 
Decoupling queue -> E                      Ex2 -> Retry queue
                      \ Target2 (failed) /                    \ Target2 (success - ack E2)
```

The same event will be enqueued twice in the retry queue. So for an event being retried, it will only deliver to 1 subscriber.

> This makes the retry timing more unpredictable

This is a valid concern and it's still about isolation. On a high level I think decoupling queue has a similar problem and comparatively we can probably have a more relaxed latency requirements for retry. We can also try some tricks like requeue instead of unack.

**Comment by ericlem** [comment]
We did.  One of the biggest issues with a shared retry subscription is that your only choice for controlling retry rate to a consumer is the retry rate of the underlying queue.  IE, if you have 50000 events enqueued for a target that hasn't been up for 36 hours, you have to keep retrying them at the normal event retry rate(and each of these pulls also incurs a pub sub pull cost).  If you have seperate subscriptions you can (for instance) say that you're only going to try a single pull every minute 5 minutes until something succeeds.  With a shared pull you can't do that since you have to keep pulling for others to get messages through.

**Comment by grantr** [comment]
Oops I misread your comment and replied as if you'd said you prefer option 2. Sorry for misunderstanding, but thank you for writing out your summary of the solution. :grin:

> This is a valid concern and it's still about isolation.

Putting my user hat on, I'm not satisfied by, "we thought we couldn't figure out how to scale this, so you'll have to deal with unpredictable retry." IMO stability of user experience under load needs to be a primary goal for a production system.

The concern about scaling one topic versus multiple topics seems valid, but I don't think it justifies reducing the utility of the system in perpetuity at this early stage. Do we think this is too hard right now, or too hard forever?

**Comment by ericlem** [comment]
@Harwayne 
FYI

**Comment by yolocs** [comment]
> Putting my user hat on, I'm not satisfied by, "we thought we couldn't figure out how to scale this, so you'll have to deal with unpredictable retry." 

I'm not implying that. We will have deal with the scaling problem either way. But if a user really cares about isolation to avoid noisy neighbors, I'm leaning towards to "let them have their own broker".

**Comment by yolocs** [comment]
> We did. One of the biggest issues with a shared retry subscription is that your only choice for controlling retry rate to a consumer is the retry rate of the underlying queue. IE, if you have 50000 events enqueued for a target that hasn't been up for 36 hours, you have to keep retrying them at the normal event retry rate(and each of these pulls also incurs a pub sub pull cost). If you have seperate subscriptions you can (for instance) say that you're only going to try a single pull every minute 5 minutes until something succeeds. With a shared pull you can't do that since you have to keep pulling for others to get messages through.

Thanks for reminding me. Not sure if it would complicate things or simply, but would multiple retry queues (each with longer deliver delay) help in this case?

**Comment by ericlem** [comment]
It would help, but still is a bit less control in such situations.  Overall retry rate to a client still ends up being affected by the number of messages queued for that target.  And it makes it harder to quickly pick back up and start delivering messages as soon as a client comes back up for messages enqueued in a long retry interval queue.

**Comment by grantr** [comment]
> I'm not implying that. 

Sorry for putting words in your mouth, and thank you for correcting me. Obviously nobody wants that to be what we tell users :)

> But if a user really cares about isolation to avoid noisy neighbors, I'm leaning towards to "let them have their own broker".

IIUC, with a single shared retry topic, creating another broker doesn't improve isolation, right? They'd have to create a separate data plane (which may be what you're referring to here).

**Comment by yolocs** [comment]
Sorry for not stating it clearly. Yes, it's "let them have their own data-plane". I believe it's also one of our goals to support this?

> The concern about scaling one topic versus multiple topics seems valid, but I don't think it justifies reducing the utility of the system in perpetuity at this early stage. Do we think this is too hard right now, or too hard forever?

IMO I'm less concerned about scaling (because it's going to be somewhat complicated anyway). If we're fine with the complexity introduced to the controller (provision/recycle pubsub resources) and fanout service (dynamically add/remove pulls), I think we should just go for decoupling queue per broker.

**Comment by grantr** [comment]
> If we're fine with the complexity introduced to the controller (provision/recycle pubsub resources) and fanout service (dynamically add/remove pulls) and ingress service (it now needs to know the mapping between broker <-> topic)

Thanks @yolocs, this is a good summary of the complexities involved. I think these are manageable, but if we choose this path and I'm wrong we'll probably find out right away. We've done them all before in eventing and knative-gcp.

**Comment by grantr** [comment]
> I believe it's also one of our goals to support this?

This is one of my goals but I hope it's an exceptional case (and that we don't need to spend a lot of time making it simple to use).

**Comment by akashrv** [comment]
Good discussion.  My two cents on "isolation".  I don't think that having a multi-tenant shared data-plane  throws away isolation. Usually any online service will be multi-tenant and handle workloads from multiple users. In my experience I have seen isolation being a concern when it comes when we save the state  or persist user-data, rather than stateless services that handle requests from any tenant. So in this case even if tenants want isolation in future, I don't think having a shared stateless data-plane on the cluster will be a problem. But a shared topic that persists data could potentially be problematic.
Also think about user's debugging experience. We will ask them to access msgs in topics. Could that be a potential problem, if a user can see msgs from other tenants? Let's discuss more tomorrow over GVC.

About single retry topic v/s per trigger retry topic, I would lean towards per trigger topic so that retries are isolated to the offending destination.

@mikehelmick to share his thoughts too.

**Comment by grantr** [comment]
We decided on per-Broker decoupling topics, because despite not providing true isolation, the separation of per-Broker pubsub metrics and billing is useful enough to slightly outweigh any additional complexities. The preference for this strategy was slight so we may revisit this decision if unforeseen difficulties arise.

The per-Broker decoupling topics solution has these advantages:
- Per-Broker usage and cost accounting is easier using pubsub metrics and billing.
- Debugging a specific Broker by looking at the topic is easier.

And these disadvantages:
- Greater complexity of dynamically updating the set of topics to pull from. Since we also decided on per-Trigger retry topics (see below), this complexity is likely shared by the two approaches.
- More complex to scale on queue length and to manage resource usage of the pod. This complexity is also shared with per-Trigger retry topics.

These properties seemed neither advantage nor disadvantage:
- Complexity of managing multiple topics vs single topic in the controller. The need to generate a unique topic name adds complexity to the single topic case.

We also discussed whether to use a shared retry topic for all Triggers or per-Trigger retry topics. We decided on per-Trigger decoupling topics because we believe it will be easier to implement flow control for consumers consuming at different rates. The preference for this strategy was stronger than with the decoupling topic strategy, though it is still unknown how we will implement per-consumer flow control using the interfaces provided by the pubsub go client (see the [pubsub pull docs](https://cloud.google.com/pubsub/docs/pull)).

The advantages and disadvantages of the per-Trigger retry topics solution are the same as above, plus this advantage:
- Easier to implement per-consumer flow control. This is difficult with a single shared pull subscription to the shared retry topic (see [Eric's comment](https://github.com/google/knative-gcp/issues/699#issuecomment-604079136)).
