### ISSUE TITLE
#2 Broker fanout fails for recreated brokers

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#838]
**Describe the bug**
For a recreated broker, fanout fails with 
```
{"level":"error","ts":"2020-04-14T19:00:58.790Z","logger":"broker-fanout","caller":"fanout/pool.go:132","msg":"handler for broker has stopped with error","commit":"5f3eb60","broker":"default/test-broker","error":"rpc error: code = NotFound desc = Resource not found (resource=projects/conliu-kgcp-dev/subscriptions/cre-bkr_default_test-broker_a217e2d9-65e3-4a54-bcb3-d663d500158e).","stacktrace":"github.com/google/knative-gcp/pkg/broker/handler/pool/fanout.(*SyncPool).syncOnce.func2.1\n\tgithub.com/google/knative-gcp/pkg/broker/handler/pool/fanout/pool.go:132\ngithub.com/google/knative-gcp/pkg/broker/handler.(*Handler).Start.func1\n\tgithub.com/google/knative-gcp/pkg/broker/handler/handler.go:58"}
```

 **Expected behavior**
Fanout should deliver events.

 **To Reproduce**
* Create a broker, create a trigger to this broker and make sure events can be delivered
* Delete the broker and recreate it, create a trigger to the broker
* Send an event to the broker and fanout won't deliver the event to the consumers

 **Knative-GCP release version**

**Time Estimate (optional):**
2

 **Additional context**
After a broker is recreated, its decouple queue topic/subscription are updated. I looked at the targets config file in the fanout pod. It was updated with new topic/subscription for the decouple queue. It seems that fanout doesn't pick up the new DecoupleQueue config.

**Comment by capri-xiyue** [comment]
+1 I encountered the same issue when I did manual test

**Comment by yolocs** [comment]
It would be really helpful if you can provide the following context.

1. By "recreate", do you mean 1) create a broker 2) delete it 3) create the broker again with the same name?
2. Was the broker in TargetsConfig ever deleted?
3. Did the 2nd broker get new decouple topic/sub (different from the 1st broker)?
4. Was the decouple topic/sub of the 1st broker ever deleted?

I suspect the problem lies at:

https://github.com/google/knative-gcp/blob/c7e834b0b446177475915c025a5b01f38a35690f/pkg/broker/handler/pool/fanout/pool.go#L114-L117

If it sees an existing handler for a broker, it won't update the existing handler (we can fix this). So if the broker in TargetsConfig was never deleted (asked in Q-2), it will skip any future self-reconcile. However, if the answer to Q-4 is yes, then the handler of the 1st broker should stop and in the next sync it should recreate the handler with the new decouple topic/sub.

**Comment by liu-cong** [comment]
I believe most the questions can be answered from the description but I will answer them more explicitly.



> 
> 1. By "recreate", do you mean 1) create a broker 2) delete it 3) create the broker again with the same name?

3)

> 2. Was the broker in TargetsConfig ever deleted?

No, but the decouple topic is updated with a new one.

> 3. Did the 2nd broker get new decouple topic/sub (different from the 1st broker)?

Yes

> 4. Was the decouple topic/sub of the 1st broker ever deleted?

Yes. The controller deletes the topic once broker is deleted. If you recreate the broker, the controller will create a new decouple topic.

**Comment by yolocs** [comment]
How about subscription? Does controller deletes the decouple subscription?

**Comment by liu-cong** [comment]
Yes it also deletes the pull sub.
