### ISSUE TITLE
Add generation number to broker-targets config

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#913]
**Problem**
Right now each data plane pod has its own generation of the configmap. The generation is incremented every time the configmap is updated. However, there is no guarantee that all data plane pods have the same generation number.

Instead,
- controller increments the gen number on each update as a field in the broker targets configmap
- controller also updates the gen number as an annotation on the data plane pods

This is helpful to debug whether the data plane has the same generation of the configmap. See https://github.com/google/knative-gcp/pull/907#discussion_r412510724

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
Just to clarify, is this issue also suggesting that we add the generation number to the serialized targets config?

**Comment by liu-cong** [comment]
> Just to clarify, is this issue also suggesting that we add the generation number to the serialized targets config?

Yes this is also a nice to have. Especially when new pods may not get the generation as annotation. Updated the description.

**Comment by grantr** [comment]
Also add a timestamp to configmap so the data plane pods can calculate the delay for #1443.

**Comment by yolocs** [comment]
This appears to be a little bit trickier than expected. If we blindly add generation and timestamp to the configmap, it will cause unnecessary configmap updates because timestamp (and potentially generation depends on how we generate it) will always be different from the one in the existing configmap.

One possible approach: add timestamp/generation with a separate config key in the data. When reconciling the configmap, we need to skip comparing the timestamp/generation. These values will be in the same volume mount and be accessible by the broker components.

**Comment by grantr** [comment]
Seems like a good idea to separate the timestamp into a different file, since it's really intended to communicate data about the configmap mechanism rather than event routing data. Generation I could see being used either way, but we can always move it into event routing later when we have a use for it.
