### ISSUE TITLE
Investigate BrokerCell Controller Scaling with Many Triggers

### ISSUE THREAD

**Issue by ian-mi** [google/knative-gcp#935]
**Describe the bug**
The BrokerCell reconciler will do the following everytime a broker or trigger is updated:
1. list all brokers and triggers in the broker cell and regenerate targets config.
2. regenerate the broker cell's targets config.
3. read and parse the existing targets configmap.
4. update the configmap when changed.

This is likely to scale poorly with a large number of triggers, but it's not clear at what point this will become a bottleneck. Once implemented we should investigate the scalability and overhead of this approach.

 **Expected behavior**
Ideally the cost of reconciling a single trigger would not scale with the size of the brokercell.

 **Additional context**
PR #914 prototypes a process which can efficiently cache a broker cell's config and efficiently update the configuration of a single broker. It could also be extended to accept updates of individual trigger config updates.

It may also help to split the targets configmap into multiple files so that individual broker config files can be patched without rewriting the entire configmap.

**Comment by liu-cong** [comment]
Instead of listing all brokers and triggers, we could have 2 WorkQueues in the brokercell controller that maintains the updated brokers/triggers. In the reconciliation loop the controller will try to drain the queues and construct configmap updates.

We may still want to a full scan to mitigate event losses after certain amount of time since last scan.
