### ISSUE TITLE
Clarify the broker-targets contract in unhappy case

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#939]
**Problem**
1. Clarify what the config should be in the unhappy cases 
2. Have the controller **Validate** the config before saving the configmap 
3. Data plane should adapt accordingly

* If the broker is deleted
  * should it be deleted from config?
  * or mark it as DELETED? should the DecoupleQueue be nil?
* If a new broker is not reconciled successfully (e.g., failed to create/delete decouple topic)
  * mark it as NOT_READY?
  * should the DecoupleQueue be nil?
* Similar question for triggers

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
* behavior clarified
* unit tested

**Tasks**
* A data validation module for the config
* controller, data plane should use the same validation

cc @grantr @yolocs

**Comment by liu-cong** [comment]
related discussion: https://github.com/google/knative-gcp/pull/934#discussion_r414668238

**Comment by grantr** [comment]
Some possible answers based on previous discussions and decisions:

If the broker is deleted it should be deleted from targets config along with all its trigger targets. This aligns with the current strategy mentioned in #828 and #904 of immediately deleting all broker and trigger resources when a broker is deleted. Similarly, when a Trigger is deleted it should be deleted from its Broker's targets config.

If a broker is not reconciled successfully (Ready status is not True) its status should be marked as NOT_READY in targets config. With #1261, the ingress uses broker status to decide whether to accept events. The decouple queue for a NOT_READY broker may be present in the config.

Trigger Ready status is trickier. Due to the dependency annotation, Trigger ready status may be used as a signal of end-to-end readiness in addition to the Broker's readiness to deliver events matching the Trigger. A Trigger that is fully ready as far as the Broker is concerned may still show as Ready=False if its dependency is not ready.

IMO, the Trigger's status in the targets config should be READY if the data plane is able to deliver an event to the Trigger's subscriber, since that's the readiness the fanout and retry services care about. I believe this is equivalent to TopicReady==True && SubscriptionReady==True.

**Comment by yolocs** [comment]
I fully agree with what @grantr said above. Also I don't think trigger state in the config is used today.
