### ISSUE TITLE
Deployment controller needs to watch  'Create' secret

### ISSUE THREAD

**Issue by grac3gao** [google/knative-gcp#971]
**Problem**
After #825 get merged, in the init state, if the user choose to use K8S Secret, once the real secret is in, the controller needs restart to take that secret in. Thus, we probably need to investigate for letting the controller also listens to "Create" that specific secret.

 @capri-xiyue mentioned that last time when she developed it, if the deployment controller listens to "Create" specific secret, it will result in infinite loop.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
deployment controller will watch  'Create' secret, and force a restart for the controller pod.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment]
I believe the restart loop is caused by the informer cache sync on startup. During the initial sync, informers send a create event for every watched object (like global resync). The reconciler will always get a create event for the secret immediately after starting.

If this is the case, then the reconciler needs to check if a Secret create event actually requires a restart, perhaps by checking the state of the client or the credentials volume.
